version: '3'
services:
  mysql-dev:
    image: mysql:5.7.26
    environment:
      MYSQL_USER: "root"
      MYSQL_DATABASE: "suggestions"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - "mysql-dev"
    command: bash -c "./wait-for-it.sh mysql-dev:3306 && npm run db:setup && npm run start"